### ISSUE TITLE
probe segmentation in whole-brain data

### ISSUE THREAD

**Issue by Sepidak** [SainsburyWellcomeCentre/neuro#13]
outline and measure the length of the probe in different brain regions. e.g 0-500 um SC, 501-1200 um RSPg, 1201-1800 RSPd.

**Comment by adamltyson** [comment]
Brief plan:
* Run amap as normal, and assume that the data can be visualised on the downsampled data.
* Outline the probe track by adding points in a napari viewer.
* Join the dots (possibly with some kind of fit)
* Analyse length of the probe in each brain region 
* Allow 2D visualisation in napari (maybe add to amap_vis) and 3D vis in brainrender

**Comment by adamltyson** [comment]
Prototype added to `neuro`. Install with `pip install --upgrade --pre`. Basic docs [here](https://docs.cellfinder.info/neuro/standalone-tools/manual-segmentation)

Overview:
* Run amap, passing the channel with the track to segment to the `--downsample` flag
* Run `manual_seg` passing the downsampled image to be segmented, and the amap output directory
* Trace the track in the GUI:
![GUI](https://user-images.githubusercontent.com/13147259/83886889-9868ba80-a73f-11ea-8ec0-9e0d2c8a525f.png)
* It will then perform spline interpolation, and you can save where each region of the track is:

| Track position                 | Region ID | Acronym  | Name   |
|-------------------------|--------|---------|--------------------------------|
| 41                      | 593    | VISp1   | Primary visual area, layer 1   | 1" 
| 42                      | 593    | VISp1   | Primary visual area, layer 1   | 1"   |
| 43                      | 593    | VISp1   | Primary visual area, layer 1   | 1"   |
| 44                      | 593    | VISp1   | Primary visual area, layer 1   | 1"   |
| 45                      | 593    | VISp1   | Primary visual area, layer 1   | 1"   |
| 46                      | 593    | VISp1   | Primary visual area, layer 1   | 1"   |
| 47                      | 821    | VISp2/3 | Primary visual area, layer 2/3 | 1"   |
| 48                      | 821    | VISp2/3 | Primary visual area, layer 2/3 | 1"   |
| 49                      | 821    | VISp2/3 | Primary visual area, layer 2/3 | 1"   |
| 50                      | 821    | VISp2/3 | Primary visual area, layer 2/3 | 1"   |
| 51                      | 821    | VISp2/3 | Primary visual area, layer 2/3 | 1"   |

* You can then visualise in 3D in brainrender:
![3D](https://user-images.githubusercontent.com/13147259/83887324-32c8fe00-a740-11ea-9682-2b06b60113f5.png)

**Comment by adamltyson** [comment]
Added in [Version 0.3.14](https://github.com/SainsburyWellcomeCentre/cellfinder/releases/tag/v0.3.14),
