### ISSUE TITLE
segmented_regions directory needs to be created beforehand

### ISSUE THREAD

**Issue by chrytsi** [SainsburyWellcomeCentre/neuro#28]
The segmented_regions directory needs to be created prior to saving any created regions in a given sample. If not already created beforehand an error is thrown up upon attempt to save (see txt file). Once error occurs, saving is not possible anymore even if directory is created.

[neuro_error_segmented_regions_directory.txt](https://github.com/SainsburyWellcomeCentre/neuro/files/4523810/neuro_error_segmented_regions_directory.txt)

**Comment by adamltyson** [comment]
This should be fixed in a new version (likely released tomorrow).

**Comment by adamltyson** [comment]
Fixed in d2202a89a4cc820ff2a76c65347e6f2c5a99ba35
