### ISSUE TITLE
saving of regions created posthoc not possible

### ISSUE THREAD

**Issue by chrytsi** [SainsburyWellcomeCentre/neuro#29]
Once a number of regions is created and saved, re-running manual_region_seg will correctly load these. Further addition of new regions is possible, saving any newly created, however, throws up an error (see txt file). Upon closing napari viewer preview in brain render displays only one region (even if two have already been created and saved).

[neuro_bug_save_region_added_posthoc.txt](https://github.com/SainsburyWellcomeCentre/neuro/files/4523850/neuro_bug_save_region_added_posthoc.txt)

**Comment by adamltyson** [comment]
There's some weird windows stuff going on. Might take me a while to look into this.

**Comment by adamltyson** [comment]
I preferred the old title. Like it worked when a PI tried it, but failed for postdocs.

**Comment by adamltyson** [comment]
Anyway, fixed in d2202a89a4cc820ff2a76c65347e6f2c5a99ba35
