### ISSUE TITLE
vtkplotter -> vedo 

### ISSUE THREAD

**Issue by adamltyson** [SainsburyWellcomeCentre/neuro#38]
See [brainrender issue](https://github.com/BrancoLab/BrainRender/issues/79).

Once brainrender changes to use vedo rather than vtkplotter, pin the new version of brainrender, and change neuro's vtkplotter calls to vedo.

**Comment by FedeClaudi** [comment]
I've changed brainrender to vedo in the development branch, will soon publish to master branch and put on pypi

**Comment by adamltyson** [comment]
Fixed in [brainreg-segment](https://github.com/brainglobe/brainreg-segment). The manual segmentation tools here will not be updated.
