### ISSUE TITLE
track fit doesn't appear at first

### ISSUE THREAD

**Issue by velezmat** [SainsburyWellcomeCentre/neuro#41]
After opening the GUI, loading the project and adding a track_0, pressing “trace track" doesn’t create a track_0_fit.  In order to see the track_0_fit, saving needs to be done first and then press trace track again.  This then shows the track_0_fit.

**Comment by adamltyson** [comment]
for `manual_seg`

**Comment by adamltyson** [comment]
Fixed in [brainreg-segment](https://github.com/brainglobe/brainreg-segment). The manual segmentation tools here will not be updated.
