### ISSUE TITLE
Error fitting crashes GUI

### ISSUE THREAD

**Issue by velezmat** [SainsburyWellcomeCentre/neuro#42]
If a track has only 3 points, then press save, then press trace track, the GUI crashes with an error: TypeError: m > k must hold.

**Comment by adamltyson** [comment]
for `manual_seg`

**Comment by adamltyson** [comment]
Fixed in [brainreg-segment](https://github.com/brainglobe/brainreg-segment). The manual segmentation tools here will not be updated.
