### ISSUE TITLE
No module named 'brainrender.Utils.image'

### ISSUE THREAD

**Issue by horsto** [SainsburyWellcomeCentre/neuro#44]
Hi! When using the command line call `manual_seg` the following error occurs: 
```
  File "/opt/miniconda3/envs/analysis/lib/python3.6/site-packages/neuro/visualise/brainrender_tools.py", line 3, in <module>
    from brainrender.Utils.image import reorient_image, marching_cubes_to_obj
ModuleNotFoundError: No module named 'brainrender.Utils.image'
```

**Comment by adamltyson** [comment]
Thanks for pointing this out, I'll aim to fix it this week. 

In the meantime, it should work if you install an older version of brainrender.

**Comment by adamltyson** [comment]
Hi @horsto, this should be fixed by installing `pip install neuro==0.0.19`

**Comment by horsto** [comment]
it's fixed, thanks!

**Comment by adamltyson** [comment]
Reopening this. There are lots of changes in brainrender that I didn't know about, so nearly all of `manual_seg` is broken. 

For now, the only solution is to roll back to `neuro==0.0.16` and `brainrender==0.4.0.0`.

**Comment by horsto** [comment]
I see, thanks for checking this. 
I will create an environment with just those versions. As long as I can get an .obj export to use further.

**Comment by adamltyson** [comment]
I've moved the update to `brainrender==1.0.0.0` to [here](https://github.com/SainsburyWellcomeCentre/neuro/issues/47).

`manual_seg` should now work. A new version (`0.0.20`) will be released in a few minutes that pins `brainrender==0.4.0.0`.

Sorry for this hassle, the tools in `neuro` are at a very early stage.

**Comment by horsto** [comment]
Thanks, and no worries!
