### ISSUE TITLE
Using reference brain without registered data in manual_seg

### ISSUE THREAD

**Issue by horsto** [SainsburyWellcomeCentre/neuro#46]
I only just started using these tools, so please excuse my ignorance. My goal is to get a "volume/region" rendered in `brainrender` which I manually annotated somehow. I used sharptrack, however, this doesn't quite fit my need since it is not probe lesions I track but larger areas of cortical tissue. The ultimate goal would be to go through https://github.com/slicereg/slicereg to register my 2D histology and then annotate in a tool like `manual_seg`. However, it would already help me to annotate "by eye", meaning, to search for a the right plane in the mouse reference brain and roughly paint in boundaries of the regions I want to mark. While far from being perfect, this would enable me to coarsely summarise data across multiple animals. 

My question therefore is: Do you think it's possible to "just" load the reference brain (allen mouse atlas (res. 25um) or else) and use `manual_seg` to segment out regions? I want to be able to scroll through the brain from medial to lateral (in sagittal plane) and paint in regions as I scroll, then export and render in brainrender. In Napari it might be even possible to load in my histology as half-transparent overlay somehow so I can directly compare (otherwise I'd just open my histology in another window and find the best match by eye). I'd appreciate any comments!

**Comment by adamltyson** [comment]
Hi @horsto. This is certainly possible, but not yet implemented. 

It might take me a while to add this myself, because I won't be adding any new features to this version of `manual_seg`, as it will in the future be based on [brainreg](https://github.com/brainglobe/brainreg) and the atlases provided by [bg-atlasapi](https://github.com/brainglobe/bg-atlasapi). This will also be the version that will work with slicereg.

If you wanted to do this, I can see two options:
* Register the allen atlas with itself using [amap](https://github.com/SainsburyWellcomeCentre/amap-python) and use `manual_seg` as documented.
* Load the allen atlas stack into napari, annotate your region, reorient, and export as `.obj` for brainrender yourself

If you think you might end up needing to use these tools a lot, I'd welcome a PR to include this functionality (I can go through what would be needed).

Cheers,
Adam

**Comment by horsto** [comment]
Thanks a lot for your fast reply! 
> Register the allen atlas with itself using amap and use manual_seg as documented.

Can I just export the reference brain via `brainio.to_nii` and load it in manual_seg or do I have to go through amap? 

> ... reorient, and export as .obj for brainrender yourself

I think this might be more complicated (?) since I ideally want to use the region / volume making functions of manual_seg and its export to .obj capability? (Having never used manual_seg I am just assuming that is how it works...).

**Comment by adamltyson** [comment]
> Can I just export the reference brain via brainio.to_nii and load it in manual_seg or do I have to go through amap?

I'm not sure what the easiest way would be (there's nothing designed to do this). You could either download amap (`pip install amap`), then download the atlas (`amap_download`). The atlas image would then be found at `~/.amap/atlas/allen_2017_10um/brain.nii`. You might have to resave this image as tiff though (using python or FIJI).

You could also install [bg-atlasapi](https://github.com/brainglobe/bg-atlasapi). You could then fetch the atlas (as tif) by running `brainglobe install -a allen_mouse_10um`. The image would then be found at `~/.brainglobe/allen_mouse_10um_v0_3/reference.tiff`. I recommend this option, for no other reason than `brainglobe` is a package that all of brainrender/cellfinder/neuro etc. will use for the foreseeable future, and the `amap_download` functionality will be deprecated soon.

**Comment by FedeClaudi** [comment]
@horsto since you're using `brainrender` already you should have `bg-atlaspi` installed already, so you can just download the atlas if you choose to use that ;)

**Comment by adamltyson** [comment]
@FedeClaudi - A few people have now asked me for something like this (i.e. directly annotate on the reference image, not necessarily their data). Considering we have all the "building blocks" to do this (`bg-atlasapi` -> `napari` -> `brainrender`), it might be worth making a standalone tool (and not rely on `manual_seg` or any of the cellfinder stuff). 

Do you think it's worth doing?

**Comment by horsto** [comment]
Thanks for your suggestions! I am stuck now - maybe you can help? 
I loaded the reference brain with 
`atlas = BrainGlobeAtlas("allen_mouse_10um")` and `reference_brain = atlas.reference`. 

Then I thought I'd just export this as .nii with `brainio.to_nii(reference_brain, '~/Desktop/fun_with_brainrender/reference_manual_seg/reference_brain.nii'` which gives me a >2Gb big file. Trying to load this in `manual_seg` runs into errors however of the kind: 

```
The image: '~/Desktop/fun_with_brainrender/reference_manual_seg/reference_brain.nii' has not been transformed into standard space, and so must be transformed before segmentation.

Running registration
WARNING: Traceback (most recent call last):
  File "/opt/miniconda3/envs/brainrender_old/lib/python3.6/site-packages/imlib/general/system.py", line 282, in safe_execute_command
    cmd, stdout=log_file, stderr=error_file, shell=True
  File "/opt/miniconda3/envs/brainrender_old/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/opt/miniconda3/envs/brainrender_old/lib/python3.6/site-packages/imlib/bin/nifty_reg/osX/reg_resample -cpp ~/Desktop/fun_with_brainrender/reference_manual_seg/inverse_control_point_file.nii -flo ~/Desktop/fun_with_brainrender/reference_manual_seg/reference_brain.nii -ref ~/Desktop/fun_with_brainrender/reference_manual_seg/brain_filtered.nii -res ~/Desktop/fun_with_brainrender/reference_manual_seg/manual_segmentation/image_standard_space.nii' died with <Signals.SIGSEGV: 11>.
```
and others after that.
Two files are created (`inverse_transform_error.txt` and `inverse_transform_log.txt`) where only the first one has text: 
``` ** ERROR (nifti_image_read): failed to find header file for '~/Desktop/fun_with_brainrender/reference_manual_seg/brain_filtered.nii'```

**Comment by adamltyson** [comment]
So I think you don't need to use Python at all for this, it's all in command-line tools

You can download the atlas using `brainglobe install -a allen_mouse_10um`, then use the file it saves on your machine (`~/.brainglobe/allen_mouse_10um_v0_3/reference.tiff`) as input to amap. Follow the amap instructions [here](https://docs.cellfinder.info/amap/getting-started), and make sure you check out the "orientation" options, as these will likely need to be set.

You should then get an amap output directory (this is a bit stupid, as we're registering one version of the atlas to another, but it's the format `manual_seg` needs for now). When you start `manual_seg`, you need to choose `downsampled.nii` as the file to open.

Sorry this is so convoluted. it might be easier to do it yourself, I can point you to the code for saving obj files etc.

**Comment by horsto** [comment]
Thanks a lot...I will try later to follow your steps first. I will report back.

**Comment by horsto** [comment]
Just wanted to give a quick feedback: I was indeed able to follow your steps @adamltyson and the registration of the 10 micron atlas finished without errors. I was able to load it into `manual_seg` and annotate regions. However, loading the files into brainrender (regions exported as .obj) revealed that the coordinates were flipped across hemispheres *and* anterior posterior (the scale however seemed correct). Those were exactly the coordinate "flips" I introduced when running amap since I thought that would bring the reference into the correct orientation. I am a bit confused to why it registered at all and I will try to run it again without the flipping command line input (sadly it runs forever, but if this works it is at least a functioning approach for now).

**Comment by adamltyson** [comment]
Hi @horsto. Sorry I forgot, there is an issue with `manual_seg` export when your data is in certain orientations. Unfortunately this won't be fixed until `manual_seg` is integrated with `brainreg` (I'm not developing amap any further). 

If you wanted to fix this, it shouldn't be too hard to reorient the image volume prior to saving as `.obj`. Or (another) workaround would be to resave the image you're registering into a different orientation (prior to registration). I think coronal, with the first plane at the most caudal part of the brain (posterior, superior, left in the [bg-space](https://github.com/brainglobe/bg-space#usage) orientation convention).

I think it's probably easier to start from scratch with this though. `manual_seg` isn't designed for this, but most of the building blocks are there to build a dedicated tool. I'm happy to point you in the right places.

> sadly it runs forever

How long does it take? amap is slow, but it shouldn't take more than an hour (tthis is also improved with brainreg).

**Comment by horsto** [comment]
@adamltyson thanks, ok, I will try to reorient it and try again. 
I agree that it's maybe easier to start building a dedicated tool. Maybe we can communicate about this as you suggest? I am not sure where to start tbh. 

About the processing time: It took a few hours to run through the whole thing on my laptop (which isn't the fastest).

**Comment by adamltyson** [comment]
> About the processing time: It took a few hours to run through the whole thing on my laptop (which isn't the fastest).

Weird. Anyway the aim going forward with brainreg (and slicereg) is to provide options for atlas resolution. This way you can run it in a few seconds at 50um, then only run at 25um/10um when you're happy with the pipeline and can afford to wait a bit longer.

> I agree that it's maybe easier to start building a dedicated tool. Maybe we can communicate about this as you suggest? I am not sure where to start tbh.

I think we have pretty much everything to get going. @FedeClaudi - presumably if we use the atlas files from [bg-atlasapi](https://github.com/brainglobe/bg-atlasapi), then any volumes extracted as meshes will already be in the same coordinate space as brainrender expects? We just need to make sure the scaling is correct?

@horsto Do you want to send me an email (`adam.tyson@ucl.ac.uk`), and we can arrange a quick chat sometime?

**Comment by horsto** [comment]
Great, yes, will send now.

**Comment by FedeClaudi** [comment]
Hey, if the only problem is the orientation of the resulting mesh, [bg-space](https://github.com/brainglobe/bg-space) should have [tools](https://github.com/brainglobe/bg-space/blob/39b516352c8f25da8419db33c3b78e8de4cd7f79/bg_space/core.py#L326) to re-orient a set of points. Might be faster to give that a shot first (@vigji  would be the person to talk to about this). 

For an example of how to use it, check bg-atlas's code for creating atlases:
https://github.com/brainglobe/bg-atlasapi/blob/8778dbd10ef07a642fc8203c4b1b528ad83a9d3f/atlas_gen/wrapup.py#L147


The resulting pipeline will be a bit of patch-work, but it might be enough before proper tools are developed.

**Comment by adamltyson** [comment]
Hi @horsto, following our chat about building a dedicated tool for this, I'm closing this issue. Feel free to get in touch whenever.
